{% set name = "uvicore" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/uvicore-{{ version }}.tar.gz
  sha256: 5d659c34c0ecf0d4fd444996af6ed0ce23737a95a5428b9d218092e1d99d7376

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7,<4.0
    - poetry-core >=1.0.0
  run:
    - aiohttp >=3.9.0,<3.10.0
    - anyio >=4.3.0,<4.4.0
    - argon2-cffi >=23.1.0,<23.2.0
    - colored >=2.2.0,<2.3.0
    - cryptography >=42.0.0,<42.1.0
    - environs >=10.3.0,<10.4.0
    - httpx >=0.26.0,<0.27.0
    - merge-args >=0.1.0,<0.2.0
    - prettyprinter >=0.18.0,<0.19.0
    - python >=3.7,<4.0

test:
  imports:
    - uvicore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/uvicore/framework
  summary: The Async Python Framework for Artisans. An Elegant Fullstack Python Web, API and CLI Framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
