{% set name = "uvicore" %}
{% set version = "0.3.6" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uvicore-{{ version }}.tar.gz
  sha256: e254de27c07cb7d9bf3b49f4ce964e1b70d9590f01b46ce4be5a5ebb55172152

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core >=1.0.0
  run:
    - jinja2 ==3.1.5
    - aiohttp ==3.11.*
    - anyio ==4.8.*
    - argon2-cffi ==23.1.*
    - colored ==2.2.*
    - cryptography ==44.0.*
    - environs ==14.1.*
    - httpx ==0.26.*
    - merge-args ==0.1.*
    - prettyprinter ==0.18.*
    - python >={{ python_min }},<4.0
    - pydantic ==1.10.*

test:
  imports:
    - uvicore
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/uvicore/framework
  summary: The Async Python Framework for Artisans. An Elegant Fullstack Python Web, API and CLI Framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
