{% set name = "uvicore" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uvicore-{{ version }}.tar.gz
  sha256: c73dca04a14808f79bdfb0ebcb4297d211f695b6a5f7bf4f3a9dc0bcdc7e8b6a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core >=1.0.0
  run:
    - aiohttp 3.9.*
    - anyio 4.3.*
    - argon2-cffi 23.1.*
    - colored 2.2.*
    - cryptography 42.0.*
    - environs 10.3.*
    - httpx 0.26.*
    - merge-args 0.1.*
    - prettyprinter 0.18.*
    - python >={{ python_min }},<4.0
    - pydantic 1.10.*

test:
  imports:
    - uvicore
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/uvicore/framework
  summary: The Async Python Framework for Artisans. An Elegant Fullstack Python Web, API and CLI Framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
