{% set name = "uvicore" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/uvicore-{{ version }}.tar.gz
  sha256: 740f5b14e8ec1768d3b47f5665310ca3e6eb8743af030de54a04bcf18ac67b26

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7,<4.0
    - poetry-core >=1.0.0
  run:
    - aiohttp 3.9.*
    - anyio 4.3.*
    - argon2-cffi 23.1.*
    - colored 2.2.*
    - cryptography 42.0.*
    - environs 10.3.*
    - httpx 0.26.*
    - merge-args 0.1.*
    - prettyprinter 0.18.*
    - python >=3.7,<4.0
    - pydantic 1.10.*

test:
  imports:
    - uvicore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/uvicore/framework
  summary: The Async Python Framework for Artisans. An Elegant Fullstack Python Web, API and CLI Framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
