{% set name = "uvicore" %}
{% set version = "0.3.17" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uvicore-{{ version }}.tar.gz
  sha256: eaab709ce985e091808eed5f094936a2f1c06701a3e67909f768d403c6ad87cf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core >=1.0.0
  run:
    - aiohappyeyeballs ==2.6.1
    - aiosignal ==1.4.0
    - attrs ==25.3.0
    - certifi ==2025.8.3
    - cffi ==2.0.0
    - charset-normalizer ==3.4.3
    - click ==8.3.0
    - colorful ==0.5.7
    - coverage ==7.10.7
    - frozenlist ==1.7.0
    - greenlet ==3.2.4
    - h11 ==0.16.0
    - httpcore ==1.0.9
    - idna ==3.10
    - iniconfig ==2.1.0
    - mako ==1.3.10
    - markupsafe ==3.0.3
    - marshmallow ==4.0.1
    - multidict ==6.6.4
    - packaging ==25.0
    - pluggy ==1.6.0
    - propcache ==0.3.2
    - pycparser ==2.23
    - pygments ==2.19.2
    - pymysql ==1.1.2
    - python-dotenv ==1.1.1
    - sniffio ==1.3.1
    - typing_extensions ==4.15.0
    - urllib3 ==2.5.0
    - yarl ==1.20.1
    - jinja2 ==3.1.5
    - aiohttp ==3.11.*
    - anyio ==4.8.*
    - argon2-cffi ==23.1.*
    - colored ==2.2.*
    - cryptography ==44.0.*
    - environs ==14.1.*
    - httpx ==0.26.*
    - merge-args ==0.1.*
    - prettyprinter ==0.18.*
    - python >={{ python_min }},<4.0
    - pydantic ==1.10.*

test:
  imports:
    - uvicore
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/uvicore/framework
  summary: The Async Python Framework for Artisans. An Elegant Fullstack Python Web, API and CLI Framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
